name: goreleaser

on:
  push:
    tags:
      - '*'

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
            -
                name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.16
            -
                name: Install task
                run: .github/sh/install_task.sh
            -
                name: Make github config
                run: |
                    echo [user] >> ~/.gitconfig
                    echo name = olaf michaelis >> ~/.gitconfig
                    echo email = o.mic@web.de >> ~/.gitconfig
            -
                name: Run builder
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    /home/runner/.local/bin/task mod
                    /home/runner/.local/bin/task task_folder=/home/runner/.local/bin/
            -
                name: Gzip assets
                run: .github/sh/zip_builds.sh
            -
                name: Upload release binaries
                uses: alexellis/upload-assets@0.3.0
                env:
                    GITHUB_TOKEN: ${{ github.token }}
                with:
                    asset_paths: '["/tmp/gh_workflow_assets/*"]'
